//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nou {
	
	
	public partial class home {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.PlaceHolder placeholder1;
		
		protected System.Web.UI.HtmlControls.HtmlForm addReport;
		
		protected System.Web.UI.WebControls.TextBox type;
		
		protected System.Web.UI.WebControls.DropDownList severity;
		
		protected System.Web.UI.WebControls.TextBox date;
		
		protected System.Web.UI.WebControls.TextBox log;
		
		protected System.Web.UI.HtmlControls.HtmlForm deleteReport;
		
		protected System.Web.UI.WebControls.TextBox reportID;
		
		protected System.Web.UI.HtmlControls.HtmlForm filterForm;
		
		protected System.Web.UI.WebControls.DropDownList severityFilter;
		
		protected System.Web.UI.WebControls.PlaceHolder placeholder2;
	}
}
